### ISSUE TITLE
[JOSS REVIEW] Initial comments

### ISSUE THREAD

**Issue by ml-evs** [IBM/topography-searcher#3]
I am raising this issue as part of the JOSS review over at https://github.com/openjournals/joss-reviews/issues/6711, and will use it to collect any comments that pop-up as I try out the code. This is from my first non-exhaustive pass of reviewing. 

1. ~README has hardcoded version (0.0.2) on PyPI that does not match latest (0.0.3)~
2. ~The package does not have any continuous integration set up (the stub .travis.yml does nothing). This is not a requirement for JOSS but moves it down to "OK" from "Good" on this scale: https://joss.readthedocs.io/en/latest/review_criteria.html#tests. I would strongly recommend adding a simple GH actions CI if you want others to use and contribute to this code.~
3. ~After following the procedure in the README verbatim, 214 tests fail and 159 pass due to hardcoded paths. The package needs to be installed locally `pip install -e .` and the tests must be run from inside the tests directly only. Even after remedying these issues, there are still 5 test failures on my machine (details below) which seem to arise from naive FP comparisons:~

    <details>

    <summary>Test failures (click to expand)</summary>

    ```
    ========================== short test summary info ==========================
    FAILED data/test_coordinates.py::test_get_bond_angle_info - assert [109.46888152...77610308, ...] == [109.46888152...77610308, ...]
    FAILED data/test_coordinates.py::test_get_bond_angle_info2 - assert [119.99846240...81713545, ...] == [119.99846240...81713545, ...]
    FAILED data/test_coordinates.py::test_get_bond_angle_info3 - assert [107.40877470...08213614, ...] == [107.40877470...08213614, ...]
    FAILED data/test_coordinates.py::test_get_specific_bond_angle_info - assert [109.46888152...77610308, ...] == [109.46888152...77610308, ...]
    FAILED data/test_coordinates.py::test_get_specific_bond_angle_info2 - assert [107.40877470...08213614, ...] == [107.40877470...08213614, ...]
    ====================== 5 failed, 357 passed in 48.55s =======================
    ```

    </details>

4. ~There is limited documentation outside of the examples, which makes it hard to get an overview of the package and where to find certain functionality. From an initial cursory look it seems that most classes/methods have docstrings of varying usefulness, but ideally these would be combined into a searchable docs page using e.g., Sphinx or mkdocs. It is not a JOSS requirement that this is hosted online (though this is very useful) so a simple local docs build would suffice.~
5. ~I was unable to run `bayesian_optimisation.ipynb`, `dataset_roughness.ipynb` or `example_function.ipynb` due to an import error: `AttributeError: module 'topsearch' has no attribute 'potential'`. It looks like this module name was changed at some point. Following point 2) above, these examples should also be checked in the CI for each version.~
6. ~I tried the `scripts/atomic/generate_landscape/run.py` and my resulting `DisconnectivityGraph.png` does not match the one in `expected_output` at all (by my eye, at least, see below). Which should be trusted?~

    <details>
    <summary>My disconnectivity graph output (click to expand)</summary>

    ![DisconnectivityGraph](https://github.com/IBM/topography-searcher/assets/7916000/60683d66-1bf2-424a-b072-cb890630a20f)

    </details>

**Comment by LukeDicks** [comment]
@ml-evs thank you very much for the detailed feedback and recommendations, it’s much appreciated. We’ve made changes/added code and I’ve listed what we changed below, lining up with each of your previous points.
1.	Changed to `pip install topsearch` to ensure the most up-to-date version is installed.
2.	As recommended we have added Github actions CI. We now run the entire test framework for Python versions 3.10 and 3.11 on all pushes.
3.	We have modified the hard-coded paths to be relative, allowing pytest to be called from the root directory too without failures. We have also updated the tests to avoid failures due to naive floating point comparison, and these test successes are validated in the CI. Finally, we updated the installation instructions.
4.	We have generated documentation with Sphinx, which we have used to populate GitHub pages associated with the project. These pages include an index of (and search function for) all modules, along with their attributes and methods. These GH pages are now linked in the README.
5.	These notebooks were not correctly migrated to the open-source project, resulting in the many failures. We have now updated them so they work as intended. We have added a notebook for atomic clusters.
6.	These disconnectivity graphs are not too dissimilar in content despite their appearance. The results in expected_output are correct and we have updated parts of the script to ensure replication of these results.

I'll keep this issue open so you can continue to collect comments in one place.

**Comment by ml-evs** [comment]
Thanks for addressing these comments, I've started crossing them out in my OP as I go through them. One minor point, the repository now seems very large, (100 MB for a fresh git clone). I think this is because the docs build has been committed directly to the repo (fine in principle, though I would warn you that it might be worth removing this and instead adding to the docs build to your CI, so that GH pages always has the latest copy (definitely non-blocking for the paper).

Minor comments:

- The pyproject.toml lists `pytest-coverage` (a weird defunct package), I think this should be `pytest-cov` instead.
- **Dependency management**: Now that ase 3.23 has been released, it is  installed automatically when doing a fresh install. The only incompatibility seems to be that `import ase` in some of the tests files no longer works, and should be `import ase.io`. As this is a library rather than an "app", you may want to consider how best to version dependencies with poetry (or otherwise) to avoid accidental breakages (though this one is of course extremely minor). One approach for catching such errors would be to use dependabot to occasionally check for updates compatible with your `pyproject.toml` (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file), though again I don't consider this as breaking. Perhaps instead it would be nice just to mention what poetry is, and that the poetry.lock file are the tested versions of the deps (if that is true).
- Finally, you may also consider using git tags + GitHub releases to annotate the repository with the state at which the PyPI versions were released, this can be very helpful for debugging (and gives you a nice announcement for latest features that you can link to on GitHub). This can even be set up to automatically archive the state of the repository at that point on Zenodo, which is indeed a requirement of JOSS (post-acceptance).

**Comment by ml-evs** [comment]
Otherwise, I'm happy that my comments have been addressed -- the notebook examples are really nice and illustrate the package well. I'll return to the JOSS checklist and see how much more there is left to do for this review. I'll leave the issue open pending your response about my minor comments above, but feel free to close it.

**Comment by LukeDicks** [comment]
@ml-evs thank you so much for the further feedback, it's been very helpful. 

- I have now removed the static html pages and added documentation generation into the CI in order to pull documentation for the current state of the code. 

- You're right, I've changed it to `pytest-cov`.

- We've pinned the ase version now, and provided a short explanation of poetry as an alternative dependency manager, and that poetry.lock provides the specific tested version of those dependencies in the README and GitHub-pages.

- We've created a tagged release for the current v0.0.3 now. We will definitely do this going forwards for further releases.

Thanks again, I'll mark this issue as closed now.
